version: '3.7'
services:
  # The Database
  database:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    # mount a seperate volume to the mysql directory
    # this makes the database persistent
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: cah
      MYSQL_USER: cah
      MYSQL_PASSWORD: super_secret_password
      MYSQL_ROOT_PASSWORD: super_secret_root_password
    ports:
        - 33061:3306
  # The Application
  app:
    depends_on:
      - database
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www/html
    restart: always
    # map port 8080 to the apache 80
    ports:
      - 8080:80
    # map this source folder to /var/www
    # => all changes to the files will become visible in the dev server
    volumes:
      - ./:/var/www/html
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  
  # composer
  composer:
    depends_on:
      - app
    restart: "no"
    image: composer:1
    command: install
    volumes:
      - .:/app

volumes:
  dbdata: